# Generated by Django 4.2.3 on 2023-07-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FutureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "news_time",
                    models.CharField(db_index=True, max_length=30, verbose_name="time"),
                ),
                (
                    "currency",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="currency"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=30, verbose_name="description"),
                ),
                (
                    "impact",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="impact"
                    ),
                ),
                ("actual", models.CharField(max_length=30, verbose_name="actual")),
                ("forecast", models.CharField(max_length=30, verbose_name="forecast")),
                ("previous", models.CharField(max_length=30, verbose_name="previous")),
            ],
            options={
                "verbose_name": "Future Record",
                "verbose_name_plural": "Future Record",
                "db_table": "future_records",
            },
        ),
        migrations.CreateModel(
            name="NewsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "news_time",
                    models.CharField(db_index=True, max_length=30, verbose_name="time"),
                ),
                (
                    "currency",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="currency"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="description"),
                ),
                (
                    "impact",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="impact"
                    ),
                ),
                ("actual", models.CharField(max_length=30, verbose_name="actual")),
                ("forecast", models.CharField(max_length=30, verbose_name="forecast")),
                ("previous", models.CharField(max_length=30, verbose_name="previous")),
            ],
            options={
                "verbose_name": "News Record",
                "verbose_name_plural": "News Record",
                "db_table": "news_records",
            },
        ),
        migrations.CreateModel(
            name="Updates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateField(verbose_name="last update")),
            ],
        ),
    ]
