# Generated by Django 4.2.3 on 2023-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsdata",
            name="news_date",
            field=models.CharField(db_index=True, max_length=15, verbose_name="date"),
        ),
    ]
