# Generated by Django 4.2.3 on 2023-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newsdata_news_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsdata",
            name="news_date",
            field=models.DateField(db_index=True, verbose_name="date"),
        ),
    ]
