# Generated by Django 4.2.3 on 2023-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_newsdata_news_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="updates",
            name="last_future",
            field=models.DateField(null=True, verbose_name="last future"),
        ),
        migrations.AlterField(
            model_name="updates",
            name="last_update",
            field=models.DateField(null=True, verbose_name="last update"),
        ),
    ]
